Tabbed interface for method and attribute syntax
vega/altair pull request #2983
Opened 2023-03-23 03:24 UTC by joelostblom

Following up on the discussion in https://github.com/altair-viz/altair/discussions/2599#discussioncomment-5396690 to make the method-based channel option syntax the default in the docs. This PR prefers that syntax throughout the narrative documentation and includes both the method-based and attribute-syntax for the gallery examples in a tabbed interface so that there are some examples for users prefer this syntax (and since we will preserve these snippets for testing purposes anyways). The only thing left to update is the interactivity section, which I can address after #2981 is merged.

Example of how the gallery looks now:

![image](https://user-images.githubusercontent.com/4560057/227093860-4964f396-e4e1-4885-9d02-73867f5467a5.png)

2023-03-26 11:15 UTC, binste requested changes
Awesome to have the whole documentation show the method-based approach! I use the new syntax myself all the time and find it very convenient.

Although it's still a draft, I already reviewed the suggested changes so far. I can go through the interactivity section as well once it's ready.

2023-03-26 20:29 UTC, joelostblom reviewed
Great, thank you! I accepted all your changes and will ping once the interactive part is merged and I have updated this PR.

2023-03-26 20:29 UTC, joelostblom commented on doc/user_guide/encodings/index.rst
> +        alt.X('site:N').sort(field='yield', op='max')
Yes, I didn't see a change in the sort order in the current docs with `min`:

![image](https://user-images.githubusercontent.com/4560057/227802787-cd4693a4-bc91-4437-97a7-51ed00fac510.png)

2023-03-27 21:49 UTC, joelostblom commented
@binste I updated the interactive page in the docs now too, so this PR is ready for full review.

2023-03-27 21:49 UTC, joelostblom commented
@binste I updated the interactive page in the docs now too, so this PR is ready for full review.

2023-03-29 17:08 UTC, binste approved these changes

2023-03-29 17:48 UTC, merged

2023-03-29 19:09 UTC, mattijn commented
I've this error/warning while building the docs locally:
```
C:\Notebooks\mattijn\altair\sphinxext\altairplot.py:251: UserWarning: altair-plot: C:\Notebooks\mattijn\altair\doc\user_guide\marks\errorband.rst:157 Code Execution failed:SyntaxError: invalid syntax (<ast>, line 10)
  warnings.warn(message)
```
That is around here: https://github.com/altair-viz/altair/blob/master/doc/user_guide/marks/errorbar.rst?plain=1#L157

Not sure why this leads to a syntax error.

You do not have this message?

2023-03-30 04:44 UTC, joelostblom commented
Good catch, fix in https://github.com/altair-viz/altair/pull/3004